import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NProgressProvider from "@/components/NProgressProvider";

const dmSans = Work_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased`}
      >
        <NProgressProvider />
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
